### ISSUE TITLE
using PatrolJS for player control

### ISSUE THREAD

**Issue by waldenn** [nickjanssen/PatrolJS#1]
Hi,

Thanks for this interesting library.

I have a question: Can the PatrolJS API be used (or adapted) for the navigation of the player itself (not just the NPCs)? It seems to me the relevant data is there in some form to do this.

I am trying to learn how to build a very simple FPS game:

  http://spirare.js.org/app/examples/first-person-navmesh/index.html
  https://github.com/waldenn/spirare/

The issue I am running into is that I would like to add basic collision detection and walking-through-terrain/buildings, but that the existing physics libraries don't perform at all on my older graphics card. I am hoping there is a bit simpler way to get there. Any pointers welcome.

Thanks,

Waldenn

**Comment by nickjanssen** [comment]
Hi @waldenn sorry for my late reply, I didn't get notifications for some reason.

It's an interesting question...it might actually be possible yeah. You could use the movement vector of the player, pass it into the library as your destination target (e.g. player.position + movement vector) and then use the result vector of the library to actually move your player. Does that make sense?

Very interesting idea actually!

**Comment by waldenn** [comment]
Hi,

No problem. I don't have the time to look into this now, but might have a go at trying it out later. If it works I will let you know.

Thanks for the feedback.

**Comment by nickjanssen** [comment]
@waldenn did you get a chance to try it out? I'll close this for now :)

**Comment by waldenn** [comment]
No not yet. Thanks.

**Comment by donmccurdy** [comment]
To anyone curious, I got this working reasonably well by adding a `clampStep(start, end, node, ...)` method to the library, using the node/zone data PatrolJS creates. Source code [here](https://github.com/donmccurdy/three-pathfinding/blob/v0.4.0/src/index.js#L304-L382). I didn't want to use `findPath()` because it seemed likely to have issues at the edges of the navmesh.

Background reading: [Constrained Movement Along Navmesh pt. 3](http://digestingduck.blogspot.com/2010/07/constrained-movement-along-navmesh-pt-3.html?m=1)
